name: Push Docker Images to DockerHub

on:
  push:
    branches: [ main ]
    paths:
      - 'images-levy001/**'
      - 'images-zgsm/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'images-levy001/**'
      - 'images-zgsm/**'
  workflow_dispatch:

jobs:
  push-levy001-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub (Levy001)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Process Levy001 Docker images
      run: |
        echo "开始处理 images-levy001 目录中的 Docker 镜像..."

        # 检查images-levy001目录是否存在
        if [ ! -d "images-levy001" ]; then
          echo "images-levy001 目录不存在，跳过处理"
          exit 0
        fi

        # 查找所有.tar文件
        tar_files=$(find images-levy001 -name "*.tar" -type f)

        if [ -z "$tar_files" ]; then
          echo "images-levy001 目录中没有找到.tar文件"
          exit 0
        fi

        # 处理每个tar文件
        for tar_file in $tar_files; do
          echo "处理镜像文件: $tar_file"

          # 加载镜像
          docker load -i "$tar_file"

          # 从文件名推断镜像名和标签
          filename=$(basename "$tar_file" .tar)

          # 获取加载的镜像列表
          loaded_images=$(docker load -i "$tar_file" 2>&1 | grep "Loaded image" | sed 's/Loaded image: //')

          if [ -z "$loaded_images" ]; then
            echo "无法确定加载的镜像名称，跳过 $tar_file"
            continue
          fi

          # 处理每个加载的镜像
          echo "$loaded_images" | while read -r image_name; do
            if [ -n "$image_name" ]; then
              echo "准备推送镜像: $image_name (Levy001 账户)"

              # 检查镜像是否已存在于DockerHub
              if docker manifest inspect "$image_name" > /dev/null 2>&1; then
                echo "镜像 $image_name 已存在于 DockerHub (Levy001)，跳过推送"
              else
                echo "推送镜像: $image_name (Levy001 账户)"
                if docker push "$image_name"; then
                  echo "成功推送镜像: $image_name (Levy001 账户)"
                else
                  echo "推送镜像失败: $image_name (Levy001 账户)"
                  exit 1
                fi
              fi
            fi
          done
        done

        echo "Levy001 账户的镜像处理完成"

    - name: Clean up Levy001
      run: |
        echo "清理本地镜像..."
        docker system prune -f

  push-zgsm-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub (ZGSM)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_ZGSM }}
        password: ${{ secrets.DOCKERHUB_TOKEN_ZGSM }}

    - name: Process ZGSM Docker images
      run: |
        echo "开始处理 images-zgsm 目录中的 Docker 镜像..."

        # 检查images-zgsm目录是否存在
        if [ ! -d "images-zgsm" ]; then
          echo "images-zgsm 目录不存在，跳过处理"
          exit 0
        fi

        # 查找所有.tar文件
        tar_files=$(find images-zgsm -name "*.tar" -type f)

        if [ -z "$tar_files" ]; then
          echo "images-zgsm 目录中没有找到.tar文件"
          exit 0
        fi

        # 处理每个tar文件
        for tar_file in $tar_files; do
          echo "处理镜像文件: $tar_file"

          # 加载镜像
          docker load -i "$tar_file"

          # 从文件名推断镜像名和标签
          filename=$(basename "$tar_file" .tar)

          # 获取加载的镜像列表
          loaded_images=$(docker load -i "$tar_file" 2>&1 | grep "Loaded image" | sed 's/Loaded image: //')

          if [ -z "$loaded_images" ]; then
            echo "无法确定加载的镜像名称，跳过 $tar_file"
            continue
          fi

          # 处理每个加载的镜像
          echo "$loaded_images" | while read -r image_name; do
            if [ -n "$image_name" ]; then
              echo "准备推送镜像: $image_name (ZGSM 账户)"

              # 检查镜像是否已存在于DockerHub
              if docker manifest inspect "$image_name" > /dev/null 2>&1; then
                echo "镜像 $image_name 已存在于 DockerHub (ZGSM)，跳过推送"
              else
                echo "推送镜像: $image_name (ZGSM 账户)"
                if docker push "$image_name"; then
                  echo "成功推送镜像: $image_name (ZGSM 账户)"
                else
                  echo "推送镜像失败: $image_name (ZGSM 账户)"
                  exit 1
                fi
              fi
            fi
          done
        done

        echo "ZGSM 账户的镜像处理完成"

    - name: Clean up ZGSM
      run: |
        echo "清理本地镜像..."
        docker system prune -f